apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: poultry-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - backup/postgres-backup-cronjob.yaml
  - network-policies.yaml
  - redis.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: poultry-platform
  app.kubernetes.io/managed-by: kustomize

images:
  - name: poultry-platform/backend
    newTag: latest
