apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: poultry-platform
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              env:
                - name: PGHOST
                  value: "postgres-ha"
